CC = gcc
CFLAGS =  -Wall
FILES = linked_list.c use_linked_list.c
OBJ = linked_list.o use_linked_list.o
PROBLEM = a7_p3

all : main

# Compile from the previous source files
main: $(FILES)
	$(CC) $(CFLAGS) -o $(PROBLEM) $(FILES)

linked_list.o: linked_list.c
	$(CC) $(CFLAGS) -c linked_list.c

use_linked_list.o: use_linked_list.c
	$(CC) $(CFLAGS) -c use_linked_list.c

# Target to compile both targets linked_list.o and use_linked_list.o
compile_only: linked_list.o use_linked_list.o

# Target to link the object files together
link_only: linked_list.o use_linked_list.o
	$(CC) -o $(COMP) $(OBJFILES)

# Delete only the .o files using the wildcard pattern
delete_objects:
	rm -f *.o 

# Delete only the executable file 
delete_exe:
	rm -f $(PROBLEM)

delete_all: delete_exe delete_objects